import { Navbar } from "@/Components/Layout/navbar";
import { Sidebar } from "../../../Components/Layout/sidebar";
import React from "react";
import { MobileNavbar } from "@/Components/Layout/mobile-navbar";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <div className = "h-full">
      <Navbar/>
      <main className = "md:pl-0 pt-16 h-full">
        {children}
      </main>
      <MobileNavbar />
    </div>
  )
}
export default RootLayout;
