import { ClerkLoaded, ClerkProvider, RedirectToSignIn, SignIn, SignedIn, SignedOut } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './providers'
import "./globals.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <ClerkProvider>
        <body>{children}</body> 
    </ClerkProvider>
    </html>
  )
}
